### ISSUE TITLE
Voice.start('en-US') crashing on device (iOS 14.3)

### ISSUE THREAD

**Issue by alikareemraja** [react-native-voice/voice#290]
Hello!

I have been trying to fix this bug for a while now. The library works just fine on the Simulator, but when it is run on the phone (iPhone 7), Voice.start('en-US), I get the following error on Xcode 12:

Terminating app due to uncaught exception 'com.apple.coreaudio.avfaudio', reason: 'required condition is false: length <= _imp->_frameCapacity'

Please help!

**Comment by safaiyeh** [comment]
Thanks for the issue @alikareemraja what was the solution you ended up on?

**Comment by abeledovictor** [comment]
I'm having the same issue, no solution found so far

**Comment by alikareemraja** [comment]
The problem was specific to starting a voice recording when using Bluetooth connected Headset / Microphone. It has since then been fixed with the recent releases, I recommend you update the package and see if it works.

**Comment by DeepakM02** [comment]
Still not working after update the package.

**Comment by alitele** [comment]
anyone please have the solution for it ?
