### ISSUE TITLE
Voice.isAvailable() returns false on Android 11

### ISSUE THREAD

**Issue by DaviSena** [react-native-voice/voice#304]
Hey, 

I need some help. I have a solution using voice recognition on Android, but in Android 11 the function `Voice.isAvailable()` always returns **FALSE**.

No exceptions on Android Logcat.

Does anyone know if there is a way to make it work on Android 11?

Thanks

**Comment by boolgom** [comment]
https://developer.android.com/about/versions/11/privacy/package-visibility

Due to Android 11 change, you have to add below code in your manifest xml file.

```
<manifest...>
    <queries>
        <intent>
            <action android:name="android.speech.RecognitionService" />
        </intent>
    </queries>
   ...
```

**Comment by DaviSena** [comment]
Thanks, it works!
