### ISSUE TITLE
[Android] com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by Vinay-bhagwat** [react-native-voice/voice#331]
Hi, I am also facing the same issue. Can anybody help me out with it?

_Originally posted by @Vinay-bhagwat in https://github.com/react-native-voice/voice/issues/196#issuecomment-845974257_

**Comment by Vinay-bhagwat** [comment]
![Screenshot_20210521-193532](https://user-images.githubusercontent.com/23329099/119150655-46ae6280-ba6c-11eb-9185-26c6afe9b5f1.png)

**Comment by safaiyeh** [comment]
Closing as duplicate for https://github.com/react-native-voice/voice/issues/196
