### ISSUE TITLE
`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.

### ISSUE THREAD

**Issue by forchello** [react-native-voice/voice#357]
Good evening! I ask you for help, I have been suffering for a very long time with this problem. I am trying to run test code from your repository and I get this error:

![image](https://user-images.githubusercontent.com/72857598/136065563-e23d4d77-1983-4a1d-9d48-d737a7a5c61b.png)

You say that this is just a warning, but the sound cannot be recorded. Thank you for your time

**Comment by fbsoares-lu** [comment]
I have the same problem too.

**Comment by forchello** [comment]
> I have the same problem too.

Didn't find a solution? It's just that even the example from the repository does not work for me.

**Comment by muhammedjailam** [comment]
Adding the methods to the file removes the error! Not sure if this is the best fix!

https://github.com/software-mansion/react-native-reanimated/pull/2316/files

**Comment by O-Pessoa** [comment]
+1

**Comment by Muriel-Gasparini** [comment]
same!

**Comment by Sanath91009** [comment]
same... any updates ?

**Comment by forchello** [comment]
Hey! Try this, probably it wil help you

**Comment by Volper212** [comment]
> Adding the methods to the file removes the error! Not sure if this is the best fix!
> 
> https://github.com/software-mansion/react-native-reanimated/pull/2316/files

I don't use React Native Reanimated and I still get the warning. What to do?

**Comment by forchello** [comment]
> React Native Reanimated is only for example. You can add `LogBox.ignoreLogs(['new NativeEventEmitter()']); `  inside your component and don`t worry anymore

**Comment by forchello** [comment]
> > Adding the methods to the file removes the error! Not sure if this is the best fix!
> > https://github.com/software-mansion/react-native-reanimated/pull/2316/files
> 
> I don't use React Native Reanimated and I still get the warning. What to do? Is this a warning that doesn't change anything or do I need to fix this?

You can add `LogBox.ignoreLogs(['new NativeEventEmitter()']); ` inside your component and don`t worry anymore
