### ISSUE TITLE
Speech recognition is not working in Android 11 only

### ISSUE THREAD

**Issue by vineelk8** [react-native-voice/voice#362]
Hi all 

I just upgraded to android 11 and I'm facing the below issue while running the code. Is the anything I missed, please help if any finding

**Error:** unexpected element queries found in manifest application

As suggested I tried mentioned in the bug [#315 ](https://github.com/react-native-voice/voice/issues/315). Still facing the issue.

I also tried updating build.gradle mentioned in the bug [#stackoverlow](https://stackoverflow.com/questions/62969917/how-to-fix-unexpected-element-queries-found-in-manifest-error)

**android/build.gradle**

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 16
        compileSdkVersion = 30
        targetSdkVersion = 30
        googlePlayServicesVersion = "+"
        firebaseVersion = "+"
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.2")
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

```

Added below code in the **AndroidManifest.xml** file

```
<!-- Image capture & Speech to Text fixes -->
      <queries>
        <intent>
            <action android:name="android.speech.RecognitionService" />
        </intent>
      </queries>
```

**gradle-wrapper.properties**

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

```

**Comment by vineelk8** [comment]
> Hi all
> 
> I just upgraded to android 11 and I'm facing the below issue while running the code. Is the anything I missed, please help if any finding
> 
> **Error:** unexpected element queries found in manifest application
> 
> As suggested I tried mentioned in the bug [#315 ](https://github.com/react-native-voice/voice/issues/315). Still facing the issue.
> 
> I also tried updating build.gradle mentioned in the bug [#stackoverlow](https://stackoverflow.com/questions/62969917/how-to-fix-unexpected-element-queries-found-in-manifest-error)
> 
> **android/build.gradle**
> 
> ```
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript {
>     ext {
>         buildToolsVersion = "30.0.2"
>         minSdkVersion = 16
>         compileSdkVersion = 30
>         targetSdkVersion = 30
>         googlePlayServicesVersion = "+"
>         firebaseVersion = "+"
>     }
>     repositories {
>         google()
>         jcenter()
>         mavenCentral()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle:3.5.2")
>         classpath 'com.google.gms:google-services:4.3.4'
>         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> 
> allprojects {
>     repositories {
>         mavenLocal()
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url("$rootDir/../node_modules/react-native/android")
>         }
>         maven {
>             // Android JSC is installed from npm
>             url("$rootDir/../node_modules/jsc-android/dist")
>         }
> 
>         google()
>         jcenter()
>         maven { url 'https://www.jitpack.io' }
>     }
> }
> ```
> 
> Added below code in the **AndroidManifest.xml** file
> 
> ```
> 
>       <queries>
>         <intent>
>             <action android:name="android.speech.RecognitionService" />
>         </intent>
>       </queries>
> ```
> 
> **gradle-wrapper.properties**
> 
> ```
> distributionBase=GRADLE_USER_HOME
> distributionPath=wrapper/dists
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.0.1-all.zip
> zipStoreBase=GRADLE_USER_HOME
> zipStorePath=wrapper/dists
> ```

I made a mistake in **AndroidManifest.xml**. The queries tags should be outside of the application tag in the file. After doing the change the build ran successful

**Comment by msmith-techempower** [comment]
I am still experiencing this on Android 11. I applied the changes to the AndroidManifest.xml (and others), but voice recognition still does not work.

Interestingly, on very first load of the app onto a device, voice recognition will work *for a moment* then continually error every 5 seconds or so with `7/No match`.

**Comment by msmith-techempower** [comment]
I was notified of the closure of this issue, and wanted to add more context for anyone stumbling into this issue.

I *was* able to get `react-native-voice` to work on a brand new project using the additional steps specified here, however the specific issue I was running into was the new-as-of Anrdoid 11 permissions regarding binding to the microphone. Essentially, if [some app] is binding to the microphone, `react-native-voice` *cannot* also bind to the microphone in Android 11 - full stop. There is no setting to work around this; it is by design. Technically, this library is using Google Assistant (a separate app) under the hood to handle transcription, and so if your application is binding to the microphone, Google Assistant is disallowed to bind to it as well, and you will see the `7/No match` error as I was.

**Comment by DasSumana558025** [comment]
For android 11 , do we have any solution ?
