### ISSUE TITLE
iOS onSpeechResults outputting what should be onSpeechPartialResults.

### ISSUE THREAD

**Issue by jainnimish** [react-native-voice/voice#371]
Hello,

Whenever I try to return the **fully** recognized phrase with `onSpeechResults`, I always get what seems to be the output of `onSpeechPartialResults`. Can you please tell me why this is happening? Also, if I stop talking - this means that I am finished speaking a phrase - and begin speaking a new phrase, the library simply appends onto the string of `onSpeechResults` so I can't decode what the last complete phrase uttered by the user was. Can we get each phrase as a new object instead of just returning one object each time?

**Comment by mfkrause** [comment]
@jainnimish How did you solve this? I'm getting partial results from `onSpeechResults`, too.

**Comment by TMGoyani** [comment]
Yes I also would like to know, how you solve this problem ?

**Comment by xclidongbo** [comment]
same error. the bug is too long in ios.

**Comment by xclidongbo** [comment]
change  code 
```
// change this line code
// self.recognitionRequest.shouldReportPartialResults = YES;
self.recognitionRequest.shouldReportPartialResults = NO;
    // keep speech recognition data on device
    if (@available(iOS 13, *)) {
        self.recognitionRequest.requiresOnDeviceRecognition = YES;
    }
```
