### ISSUE TITLE
Warning Messages on Android 

### ISSUE THREAD

**Issue by khadeshyam** [react-native-voice/voice#430]
`new  NativeEventEmitter() was called with a non-null argument without the required addListener method.`

**Comment by ayushgupta-1** [comment]
I assume this error is coming on android specifically due to conflict with android's speech to text engine itself as it is not working.

 It can be turned off if you add 2 lines to ignore this warning on display.

**Comment by ayushgupta-1** [comment]
import {LogBox} from 'react-native';

Add below code into the app.js main component : 

`LogBox.ignoreLogs([
    '`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.',
    '`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.',
  ]);
`
 
Above code will only ignore showing this particular warning on device, but it will show in logs section.

There is no fix for now, but it can work for presentation or deployement purposes.
