### ISSUE TITLE
after linking getting gradle error

### ISSUE THREAD

**Issue by Akshaybagai52** [react-native-voice/voice#449]
After doing all the steps as shown in screenshot 
![image](https://github.com/react-native-voice/voice/assets/100753870/4f9265a2-28aa-48ac-b543-0d9d24225066)
I am getting this error 
![image](https://github.com/react-native-voice/voice/assets/100753870/8f4cd1dc-8207-4fb1-abd8-adc0e545e929)
can anyone help me to solve this i'm in hurry and one warning which i'm getting is this 
"warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this."

**Comment by gio-tev** [comment]
No need to manually link the library, just install it with the --save flag.

**Comment by hameezAhmad** [comment]
did --save work for you?

**Comment by hameezAhmad** [comment]
I have the same issue I tried multiple times with --save and also manual linking don't know what's the issue

**Comment by gio-tev** [comment]
> did --save work for you?

Yes it did.

If for some reason you are using Android 11 [link](https://github.com/react-native-voice/voice/issues/443#issue-1778115800)

Also do not forget to cd android && ./gradlew clean

**Comment by imadchakri** [comment]
I faced the same problem, and i solve it by adding  :    implementation project(':@react-native-community_voice') 
in android/app/build.gradle 
Notice :  that the auto-linking will add the line above in the android/build.gralde ( just remove the line from this file )
