### ISSUE TITLE
"Cannot make recognizer for sq-AL. Supported locale identifiers are..."

### ISSUE THREAD

**Issue by olsiodobashi** [react-native-voice/voice#461]
I'm using this library for a small project of mine and I need to recognize Albanian language (sq-AL). It looks like it's missing from the supported list of languages. Is there a way to add support for it? I've installed the language on both my Mac and iPhone where I'm testing the app but I'm getting the same error.

**Comment by AngadSethi** [comment]
@olsiodobashi, are you able to use your keyboard's dictation feature in Albanian? That'll tell you whether the language is supported or not.

https://developer.apple.com/documentation/speech/sfspeechrecognizer/1649889-supportedlocales#discussion

**Comment by olsiodobashi** [comment]
Ah no I'm not. So it's the device not supporting the language then, not the library.
Thanks for your reply.

**Comment by AngadSethi** [comment]
You're welcome!
