### ISSUE TITLE
Error in Android Build Process: Deprecated Configurations and Implicit Dependencies in @react-native-voice_voice Module

### ISSUE THREAD

**Issue by dulmina-jayaru** [react-native-voice/voice#473]
**### Issue Description:**
When building the project, an error occurs during the compilation of the @react-native-voice_voice module in the Android platform. The error is related to deprecated configurations and implicit dependencies in the Gradle build process.

**Error Details:**

A deprecation warning is triggered due to the use of an outdated configuration in the AndroidManifest.xml file.
Another error occurs during the packageDebugResources task, indicating problems with implicit dependencies related to tasks like compileDebugRenderscript and generateDebugResValues.

![Screenshot (434)](https://github.com/react-native-voice/voice/assets/112796306/d75429e6-be0f-4677-8fba-7e31fb9cb322)
![Screenshot (435)](https://github.com/react-native-voice/voice/assets/112796306/e8b9fd5a-f755-435d-91d2-47ec96ae4ece)

Can Anyone Help Please 🙏

**Comment by nppull** [comment]
`https://github.com/hoangphan2202/voice`

work for me
React native 0.72.7
Android API 11

**Comment by rohit-sharma-1802** [comment]
@dulmina-jayaru yes, same it is old didn't work for me as well

**Comment by AndePa01** [comment]
Getting similar when I try to build from Android Studio:

> 1: Task failed with an exception.
> -----------
> * What went wrong:
> Some problems were found with the configuration of task ':react-native-voice_voice:packageDebugResources' (type 'MergeResources').
>   - Gradle detected a problem with the following location: 'C:\project\node_modules\@react-native-voice\voice\android\build\generated\res\rs\debug'.
>     
>     Reason: Task ':react-native-voice_voice:packageDebugResources' uses this output of task ':@react-native-voice_voice:compileDebugRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
>     
>     Possible solutions:
>       1. Declare task ':@react-native-voice_voice:compileDebugRenderscript' as an input of ':react-native-voice_voice:packageDebugResources'.
>       2. Declare an explicit dependency on ':@react-native-voice_voice:compileDebugRenderscript' from ':react-native-voice_voice:packageDebugResources' using Task#dependsOn.
>       3. Declare an explicit dependency on ':@react-native-voice_voice:compileDebugRenderscript' from ':react-native-voice_voice:packageDebugResources' using Task#mustRunAfter.
>     
>     Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
>   - Gradle detected a problem with the following location: 'C:\project\node_modules\@react-native-voice\voice\android\build\generated\res\resValues\debug'.
>     
>     Reason: Task ':react-native-voice_voice:packageDebugResources' uses this output of task ':@react-native-voice_voice:generateDebugResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
>     
>     Possible solutions:
>       1. Declare task ':@react-native-voice_voice:generateDebugResValues' as an input of ':react-native-voice_voice:packageDebugResources'.
>       2. Declare an explicit dependency on ':@react-native-voice_voice:generateDebugResValues' from ':react-native-voice_voice:packageDebugResources' using Task#dependsOn.
>       3. Declare an explicit dependency on ':@react-native-voice_voice:generateDebugResValues' from ':react-native-voice_voice:packageDebugResources' using Task#mustRunAfter.
>     
>     Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

**Comment by VictorDev200** [comment]
@dulmina-jayaru Hello, did you fix the error?

**Comment by kapilkori** [comment]
I'm trying to build the project with the Android API Level 34, its giving me the same error. Can you please update the package or provide the solution for the same

Thank You

**Comment by anhtukhtn** [comment]
Try to remove the manual linking code. 
https://github.com/react-native-voice/voice/issues/489
