### ISSUE TITLE
ERROR: While building the project with Android API Level 34,A problem was found with the configuration of task ':react-native-voice_voice:packageDebugResources' (type 'MergeResources').

### ISSUE THREAD

**Issue by kapilkori** [react-native-voice/voice#519]
![Screenshot from 2024-10-07 14-12-33](https://github.com/user-attachments/assets/d3ca5e28-29ed-4b1e-9288-48d0fa0c93f4)

Since, the CompileSdkVersion and minimumSdkVersion doesn't support the newer gradle build, its giving me this error.
Can you please help me to fix this or provide me a better approach to fix this.

Thank You

**Comment by kapilkori** [comment]
![Screenshot from 2024-10-07 14-12-33](https://github.com/user-attachments/assets/d3ca5e28-29ed-4b1e-9288-48d0fa0c93f4)

Since, the CompileSdkVersion and minimumSdkVersion doesn't support the newer gradle build, its giving me this error.
Can you please help me to fix this or provide me a better approach to fix this.

Thank You

**Comment by hhyyy9** [comment]
same error

**Comment by kapilkori** [comment]
Hey @hhyyy9 ,
Looks like in the latest version you would have to add 'android.enableJetifier=true' to your gradle.properties file.
After that, close your terminal and open a fresh then try to re-bulid it again. 
Hope it helps. 
Also, this is happening with the Android.
